[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  # Add Netlify environment variables
  SANITY_PROJECT_ID = ""
  SANITY_DATASET = ""
  # Don't include SANITY_TOKEN here (set in Netlify UI)
  SECRETS_SCAN_OMIT_KEYS = "SANITY_TOKEN"

# Configure secrets scanning
[secrets_scanning]
  # Omit nitro server bundle from secrets scanning 
  # (since it will contain server-side environment variables by design)
  omit_paths = [
    ".netlify/functions-internal/server/chunks/nitro/nitro.mjs"
  ]

# Cache headers configuration
[[headers]]
  for = "/_nuxt/builds/meta/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_nuxt/builds/*"
  [headers.values]
    cache-control = "public, max-age=1, immutable"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"
